data_ingestion:
  bucket_name : "my_bucket19"
  bucket_file_name : "Hotel_Reservations.csv"
  train_ratio : 0.8
  service_account_key_path:  "D:/MLOps Project-1/keys/plated-ensign-467012-j9-d2db187b8700.json"

